// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 0,1 心跳包
type AutoId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoId) Reset()         { *m = AutoId{} }
func (m *AutoId) String() string { return proto.CompactTextString(m) }
func (*AutoId) ProtoMessage()    {}
func (*AutoId) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *AutoId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoId.Unmarshal(m, b)
}
func (m *AutoId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoId.Marshal(b, m, deterministic)
}
func (m *AutoId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoId.Merge(m, src)
}
func (m *AutoId) XXX_Size() int {
	return xxx_messageInfo_AutoId.Size(m)
}
func (m *AutoId) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoId.DiscardUnknown(m)
}

var xxx_messageInfo_AutoId proto.InternalMessageInfo

func (m *AutoId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 30,31 通信加密种子
type SeedInfo struct {
	ClientSendSeed       int64    `protobuf:"varint,1,opt,name=client_send_seed,json=clientSendSeed,proto3" json:"client_send_seed,omitempty"`
	ClientReceiveSeed    int64    `protobuf:"varint,2,opt,name=client_receive_seed,json=clientReceiveSeed,proto3" json:"client_receive_seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeedInfo) Reset()         { *m = SeedInfo{} }
func (m *SeedInfo) String() string { return proto.CompactTextString(m) }
func (*SeedInfo) ProtoMessage()    {}
func (*SeedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *SeedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeedInfo.Unmarshal(m, b)
}
func (m *SeedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeedInfo.Marshal(b, m, deterministic)
}
func (m *SeedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeedInfo.Merge(m, src)
}
func (m *SeedInfo) XXX_Size() int {
	return xxx_messageInfo_SeedInfo.Size(m)
}
func (m *SeedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SeedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SeedInfo proto.InternalMessageInfo

func (m *SeedInfo) GetClientSendSeed() int64 {
	if m != nil {
		return m.ClientSendSeed
	}
	return 0
}

func (m *SeedInfo) GetClientReceiveSeed() int64 {
	if m != nil {
		return m.ClientReceiveSeed
	}
	return 0
}

// 一般性回复payload
type BaseAck struct {
	Ret                  int64    `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseAck) Reset()         { *m = BaseAck{} }
func (m *BaseAck) String() string { return proto.CompactTextString(m) }
func (*BaseAck) ProtoMessage()    {}
func (*BaseAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *BaseAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseAck.Unmarshal(m, b)
}
func (m *BaseAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseAck.Marshal(b, m, deterministic)
}
func (m *BaseAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseAck.Merge(m, src)
}
func (m *BaseAck) XXX_Size() int {
	return xxx_messageInfo_BaseAck.Size(m)
}
func (m *BaseAck) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseAck.DiscardUnknown(m)
}

var xxx_messageInfo_BaseAck proto.InternalMessageInfo

func (m *BaseAck) GetRet() int64 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *BaseAck) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 一般性请求payload
type BaseReq struct {
	AppFrom              string   `protobuf:"bytes,1,opt,name=app_from,json=appFrom,proto3" json:"app_from,omitempty"`
	AppVer               int32    `protobuf:"varint,2,opt,name=app_ver,json=appVer,proto3" json:"app_ver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseReq) Reset()         { *m = BaseReq{} }
func (m *BaseReq) String() string { return proto.CompactTextString(m) }
func (*BaseReq) ProtoMessage()    {}
func (*BaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *BaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseReq.Unmarshal(m, b)
}
func (m *BaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseReq.Marshal(b, m, deterministic)
}
func (m *BaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseReq.Merge(m, src)
}
func (m *BaseReq) XXX_Size() int {
	return xxx_messageInfo_BaseReq.Size(m)
}
func (m *BaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_BaseReq proto.InternalMessageInfo

func (m *BaseReq) GetAppFrom() string {
	if m != nil {
		return m.AppFrom
	}
	return ""
}

func (m *BaseReq) GetAppVer() int32 {
	if m != nil {
		return m.AppVer
	}
	return 0
}

// 10, 用户登录
type UserLoginReq struct {
	BaseReq              *BaseReq `protobuf:"bytes,1,opt,name=base_req,json=baseReq,proto3" json:"base_req,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UniqueId             string   `protobuf:"bytes,3,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	ConnectTo            string   `protobuf:"bytes,5,opt,name=connect_to,json=connectTo,proto3" json:"connect_to,omitempty"`
	IsReconnect          int64    `protobuf:"varint,6,opt,name=is_reconnect,json=isReconnect,proto3" json:"is_reconnect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginReq) Reset()         { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()    {}
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}

func (m *UserLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginReq.Unmarshal(m, b)
}
func (m *UserLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginReq.Marshal(b, m, deterministic)
}
func (m *UserLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginReq.Merge(m, src)
}
func (m *UserLoginReq) XXX_Size() int {
	return xxx_messageInfo_UserLoginReq.Size(m)
}
func (m *UserLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginReq proto.InternalMessageInfo

func (m *UserLoginReq) GetBaseReq() *BaseReq {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

func (m *UserLoginReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserLoginReq) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *UserLoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserLoginReq) GetConnectTo() string {
	if m != nil {
		return m.ConnectTo
	}
	return ""
}

func (m *UserLoginReq) GetIsReconnect() int64 {
	if m != nil {
		return m.IsReconnect
	}
	return 0
}

// 11, 用户登录回复
type UserLoginAck struct {
	BaseAck              *BaseAck `protobuf:"bytes,1,opt,name=base_ack,json=baseAck,proto3" json:"base_ack,omitempty"`
	ServiceId            string   `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginAck) Reset()         { *m = UserLoginAck{} }
func (m *UserLoginAck) String() string { return proto.CompactTextString(m) }
func (*UserLoginAck) ProtoMessage()    {}
func (*UserLoginAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5}
}

func (m *UserLoginAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginAck.Unmarshal(m, b)
}
func (m *UserLoginAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginAck.Marshal(b, m, deterministic)
}
func (m *UserLoginAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginAck.Merge(m, src)
}
func (m *UserLoginAck) XXX_Size() int {
	return xxx_messageInfo_UserLoginAck.Size(m)
}
func (m *UserLoginAck) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginAck.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginAck proto.InternalMessageInfo

func (m *UserLoginAck) GetBaseAck() *BaseAck {
	if m != nil {
		return m.BaseAck
	}
	return nil
}

func (m *UserLoginAck) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

// 40, 用户踢出通知
type KickedOutAck struct {
	BaseAck              *BaseAck `protobuf:"bytes,1,opt,name=base_ack,json=baseAck,proto3" json:"base_ack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickedOutAck) Reset()         { *m = KickedOutAck{} }
func (m *KickedOutAck) String() string { return proto.CompactTextString(m) }
func (*KickedOutAck) ProtoMessage()    {}
func (*KickedOutAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{6}
}

func (m *KickedOutAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickedOutAck.Unmarshal(m, b)
}
func (m *KickedOutAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickedOutAck.Marshal(b, m, deterministic)
}
func (m *KickedOutAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickedOutAck.Merge(m, src)
}
func (m *KickedOutAck) XXX_Size() int {
	return xxx_messageInfo_KickedOutAck.Size(m)
}
func (m *KickedOutAck) XXX_DiscardUnknown() {
	xxx_messageInfo_KickedOutAck.DiscardUnknown(m)
}

var xxx_messageInfo_KickedOutAck proto.InternalMessageInfo

func (m *KickedOutAck) GetBaseAck() *BaseAck {
	if m != nil {
		return m.BaseAck
	}
	return nil
}

//用户信息
type UserInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsOnline             bool     `protobuf:"varint,3,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{7}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

//群信息
type GroupInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Online               int64    `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupInfo) Reset()         { *m = GroupInfo{} }
func (m *GroupInfo) String() string { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()    {}
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{8}
}

func (m *GroupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupInfo.Unmarshal(m, b)
}
func (m *GroupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupInfo.Marshal(b, m, deterministic)
}
func (m *GroupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInfo.Merge(m, src)
}
func (m *GroupInfo) XXX_Size() int {
	return xxx_messageInfo_GroupInfo.Size(m)
}
func (m *GroupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInfo proto.InternalMessageInfo

func (m *GroupInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupInfo) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GroupInfo) GetOnline() int64 {
	if m != nil {
		return m.Online
	}
	return 0
}

//群信息
type GroupDetail struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Members              []*UserInfo `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GroupDetail) Reset()         { *m = GroupDetail{} }
func (m *GroupDetail) String() string { return proto.CompactTextString(m) }
func (*GroupDetail) ProtoMessage()    {}
func (*GroupDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{9}
}

func (m *GroupDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupDetail.Unmarshal(m, b)
}
func (m *GroupDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupDetail.Marshal(b, m, deterministic)
}
func (m *GroupDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupDetail.Merge(m, src)
}
func (m *GroupDetail) XXX_Size() int {
	return xxx_messageInfo_GroupDetail.Size(m)
}
func (m *GroupDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupDetail.DiscardUnknown(m)
}

var xxx_messageInfo_GroupDetail proto.InternalMessageInfo

func (m *GroupDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupDetail) GetMembers() []*UserInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

//3001 获取好友列表
type GetFriendListReq struct {
	BaseReq              *BaseReq `protobuf:"bytes,1,opt,name=base_req,json=baseReq,proto3" json:"base_req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFriendListReq) Reset()         { *m = GetFriendListReq{} }
func (m *GetFriendListReq) String() string { return proto.CompactTextString(m) }
func (*GetFriendListReq) ProtoMessage()    {}
func (*GetFriendListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{10}
}

func (m *GetFriendListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendListReq.Unmarshal(m, b)
}
func (m *GetFriendListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendListReq.Marshal(b, m, deterministic)
}
func (m *GetFriendListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendListReq.Merge(m, src)
}
func (m *GetFriendListReq) XXX_Size() int {
	return xxx_messageInfo_GetFriendListReq.Size(m)
}
func (m *GetFriendListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendListReq proto.InternalMessageInfo

func (m *GetFriendListReq) GetBaseReq() *BaseReq {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

type GetFriendListAck struct {
	BaseAck              *BaseAck    `protobuf:"bytes,1,opt,name=base_ack,json=baseAck,proto3" json:"base_ack,omitempty"`
	Members              []*UserInfo `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetFriendListAck) Reset()         { *m = GetFriendListAck{} }
func (m *GetFriendListAck) String() string { return proto.CompactTextString(m) }
func (*GetFriendListAck) ProtoMessage()    {}
func (*GetFriendListAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{11}
}

func (m *GetFriendListAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendListAck.Unmarshal(m, b)
}
func (m *GetFriendListAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendListAck.Marshal(b, m, deterministic)
}
func (m *GetFriendListAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendListAck.Merge(m, src)
}
func (m *GetFriendListAck) XXX_Size() int {
	return xxx_messageInfo_GetFriendListAck.Size(m)
}
func (m *GetFriendListAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendListAck.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendListAck proto.InternalMessageInfo

func (m *GetFriendListAck) GetBaseAck() *BaseAck {
	if m != nil {
		return m.BaseAck
	}
	return nil
}

func (m *GetFriendListAck) GetMembers() []*UserInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

//3002 获取群组列表
type GetGroupListReq struct {
	BaseReq              *BaseReq     `protobuf:"bytes,1,opt,name=base_req,json=baseReq,proto3" json:"base_req,omitempty"`
	Groups               []*GroupInfo `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetGroupListReq) Reset()         { *m = GetGroupListReq{} }
func (m *GetGroupListReq) String() string { return proto.CompactTextString(m) }
func (*GetGroupListReq) ProtoMessage()    {}
func (*GetGroupListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{12}
}

func (m *GetGroupListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupListReq.Unmarshal(m, b)
}
func (m *GetGroupListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupListReq.Marshal(b, m, deterministic)
}
func (m *GetGroupListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupListReq.Merge(m, src)
}
func (m *GetGroupListReq) XXX_Size() int {
	return xxx_messageInfo_GetGroupListReq.Size(m)
}
func (m *GetGroupListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupListReq proto.InternalMessageInfo

func (m *GetGroupListReq) GetBaseReq() *BaseReq {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

func (m *GetGroupListReq) GetGroups() []*GroupInfo {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GetGroupListAck struct {
	BaseAck              *BaseAck     `protobuf:"bytes,1,opt,name=base_ack,json=baseAck,proto3" json:"base_ack,omitempty"`
	Groups               []*GroupInfo `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetGroupListAck) Reset()         { *m = GetGroupListAck{} }
func (m *GetGroupListAck) String() string { return proto.CompactTextString(m) }
func (*GetGroupListAck) ProtoMessage()    {}
func (*GetGroupListAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{13}
}

func (m *GetGroupListAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupListAck.Unmarshal(m, b)
}
func (m *GetGroupListAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupListAck.Marshal(b, m, deterministic)
}
func (m *GetGroupListAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupListAck.Merge(m, src)
}
func (m *GetGroupListAck) XXX_Size() int {
	return xxx_messageInfo_GetGroupListAck.Size(m)
}
func (m *GetGroupListAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupListAck.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupListAck proto.InternalMessageInfo

func (m *GetGroupListAck) GetBaseAck() *BaseAck {
	if m != nil {
		return m.BaseAck
	}
	return nil
}

func (m *GetGroupListAck) GetGroups() []*GroupInfo {
	if m != nil {
		return m.Groups
	}
	return nil
}

//3003 获取群成员列表
type GetGroupmembersReq struct {
	BaseReq              *BaseReq `protobuf:"bytes,1,opt,name=base_req,json=baseReq,proto3" json:"base_req,omitempty"`
	Group                int64    `protobuf:"varint,2,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupmembersReq) Reset()         { *m = GetGroupmembersReq{} }
func (m *GetGroupmembersReq) String() string { return proto.CompactTextString(m) }
func (*GetGroupmembersReq) ProtoMessage()    {}
func (*GetGroupmembersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{14}
}

func (m *GetGroupmembersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupmembersReq.Unmarshal(m, b)
}
func (m *GetGroupmembersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupmembersReq.Marshal(b, m, deterministic)
}
func (m *GetGroupmembersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupmembersReq.Merge(m, src)
}
func (m *GetGroupmembersReq) XXX_Size() int {
	return xxx_messageInfo_GetGroupmembersReq.Size(m)
}
func (m *GetGroupmembersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupmembersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupmembersReq proto.InternalMessageInfo

func (m *GetGroupmembersReq) GetBaseReq() *BaseReq {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

func (m *GetGroupmembersReq) GetGroup() int64 {
	if m != nil {
		return m.Group
	}
	return 0
}

type GetGroupmembersAck struct {
	BaseAck              *BaseAck    `protobuf:"bytes,1,opt,name=base_ack,json=baseAck,proto3" json:"base_ack,omitempty"`
	Members              []*UserInfo `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetGroupmembersAck) Reset()         { *m = GetGroupmembersAck{} }
func (m *GetGroupmembersAck) String() string { return proto.CompactTextString(m) }
func (*GetGroupmembersAck) ProtoMessage()    {}
func (*GetGroupmembersAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{15}
}

func (m *GetGroupmembersAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupmembersAck.Unmarshal(m, b)
}
func (m *GetGroupmembersAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupmembersAck.Marshal(b, m, deterministic)
}
func (m *GetGroupmembersAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupmembersAck.Merge(m, src)
}
func (m *GetGroupmembersAck) XXX_Size() int {
	return xxx_messageInfo_GetGroupmembersAck.Size(m)
}
func (m *GetGroupmembersAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupmembersAck.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupmembersAck proto.InternalMessageInfo

func (m *GetGroupmembersAck) GetBaseAck() *BaseAck {
	if m != nil {
		return m.BaseAck
	}
	return nil
}

func (m *GetGroupmembersAck) GetMembers() []*UserInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

//3004 个人聊天
type SingleChatReq struct {
	BaseReq              *BaseReq `protobuf:"bytes,1,opt,name=base_req,json=baseReq,proto3" json:"base_req,omitempty"`
	To                   int64    `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleChatReq) Reset()         { *m = SingleChatReq{} }
func (m *SingleChatReq) String() string { return proto.CompactTextString(m) }
func (*SingleChatReq) ProtoMessage()    {}
func (*SingleChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{16}
}

func (m *SingleChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleChatReq.Unmarshal(m, b)
}
func (m *SingleChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleChatReq.Marshal(b, m, deterministic)
}
func (m *SingleChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleChatReq.Merge(m, src)
}
func (m *SingleChatReq) XXX_Size() int {
	return xxx_messageInfo_SingleChatReq.Size(m)
}
func (m *SingleChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_SingleChatReq proto.InternalMessageInfo

func (m *SingleChatReq) GetBaseReq() *BaseReq {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

func (m *SingleChatReq) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *SingleChatReq) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

//3005 群聊
type GroupChatReq struct {
	BaseReq              *BaseReq `protobuf:"bytes,1,opt,name=Base_req,json=BaseReq,proto3" json:"Base_req,omitempty"`
	Group                int64    `protobuf:"varint,2,opt,name=group,proto3" json:"group,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Appoint              []int64  `protobuf:"varint,4,rep,packed,name=appoint,proto3" json:"appoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupChatReq) Reset()         { *m = GroupChatReq{} }
func (m *GroupChatReq) String() string { return proto.CompactTextString(m) }
func (*GroupChatReq) ProtoMessage()    {}
func (*GroupChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{17}
}

func (m *GroupChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupChatReq.Unmarshal(m, b)
}
func (m *GroupChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupChatReq.Marshal(b, m, deterministic)
}
func (m *GroupChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupChatReq.Merge(m, src)
}
func (m *GroupChatReq) XXX_Size() int {
	return xxx_messageInfo_GroupChatReq.Size(m)
}
func (m *GroupChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_GroupChatReq proto.InternalMessageInfo

func (m *GroupChatReq) GetBaseReq() *BaseReq {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

func (m *GroupChatReq) GetGroup() int64 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *GroupChatReq) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *GroupChatReq) GetAppoint() []int64 {
	if m != nil {
		return m.Appoint
	}
	return nil
}

func init() {
	proto.RegisterType((*AutoId)(nil), "proto.AutoId")
	proto.RegisterType((*SeedInfo)(nil), "proto.SeedInfo")
	proto.RegisterType((*BaseAck)(nil), "proto.BaseAck")
	proto.RegisterType((*BaseReq)(nil), "proto.BaseReq")
	proto.RegisterType((*UserLoginReq)(nil), "proto.UserLoginReq")
	proto.RegisterType((*UserLoginAck)(nil), "proto.UserLoginAck")
	proto.RegisterType((*KickedOutAck)(nil), "proto.KickedOutAck")
	proto.RegisterType((*UserInfo)(nil), "proto.UserInfo")
	proto.RegisterType((*GroupInfo)(nil), "proto.GroupInfo")
	proto.RegisterType((*GroupDetail)(nil), "proto.GroupDetail")
	proto.RegisterType((*GetFriendListReq)(nil), "proto.GetFriendListReq")
	proto.RegisterType((*GetFriendListAck)(nil), "proto.GetFriendListAck")
	proto.RegisterType((*GetGroupListReq)(nil), "proto.GetGroupListReq")
	proto.RegisterType((*GetGroupListAck)(nil), "proto.getGroupListAck")
	proto.RegisterType((*GetGroupmembersReq)(nil), "proto.getGroupmembersReq")
	proto.RegisterType((*GetGroupmembersAck)(nil), "proto.getGroupmembersAck")
	proto.RegisterType((*SingleChatReq)(nil), "proto.SingleChatReq")
	proto.RegisterType((*GroupChatReq)(nil), "proto.GroupChatReq")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x56, 0xe3, 0xc4, 0xb1, 0x27, 0x79, 0xd3, 0xbc, 0x4b, 0x45, 0x8d, 0x50, 0xa5, 0xb2, 0xa7,
	0xf4, 0x40, 0x0f, 0xe5, 0xc4, 0xa1, 0x87, 0x16, 0xd4, 0x12, 0xb5, 0x52, 0xa5, 0x2d, 0x45, 0x1c,
	0x40, 0x96, 0x63, 0x4f, 0xd3, 0x25, 0xc9, 0xae, 0xbb, 0xbb, 0xe9, 0x85, 0x1f, 0xc8, 0xdf, 0x42,
	0xfb, 0x61, 0xa8, 0x28, 0x82, 0xfa, 0xc0, 0x29, 0x3b, 0x5f, 0xcf, 0x33, 0xcf, 0xcc, 0xc4, 0x30,
	0x28, 0xe6, 0x28, 0xcc, 0x7e, 0xad, 0xa4, 0x91, 0xa4, 0xe7, 0x7e, 0x68, 0x06, 0xf1, 0xd1, 0xda,
	0xc8, 0x69, 0x45, 0x46, 0xd0, 0xe1, 0x55, 0xb6, 0xb1, 0xbb, 0x31, 0xe9, 0xb1, 0x0e, 0xaf, 0x68,
	0x05, 0xc9, 0x25, 0x62, 0x35, 0x15, 0xd7, 0x92, 0x4c, 0x60, 0x5c, 0x2e, 0x39, 0x0a, 0x93, 0x6b,
	0x14, 0x55, 0xae, 0x11, 0x7d, 0x66, 0xc4, 0x46, 0xde, 0x7f, 0x89, 0xa2, 0xb2, 0xd9, 0x64, 0x1f,
	0x9e, 0x84, 0x4c, 0x85, 0x25, 0xf2, 0x3b, 0xf4, 0xc9, 0x1d, 0x97, 0xfc, 0xbf, 0x0f, 0x31, 0x1f,
	0xb1, 0xf9, 0xf4, 0x25, 0xf4, 0x8f, 0x0b, 0x8d, 0x47, 0xe5, 0x82, 0x8c, 0x21, 0x52, 0x68, 0x02,
	0xae, 0x7d, 0x5a, 0xcf, 0x4a, 0xcf, 0x5d, 0x71, 0xca, 0xec, 0x93, 0x1e, 0xfa, 0x74, 0x86, 0xb7,
	0xe4, 0x19, 0x24, 0x45, 0x5d, 0xe7, 0xd7, 0x4a, 0xae, 0x5c, 0x4d, 0xca, 0xfa, 0x45, 0x5d, 0x9f,
	0x28, 0xb9, 0x22, 0xdb, 0x60, 0x9f, 0xf9, 0x1d, 0x2a, 0x57, 0xdb, 0x63, 0x71, 0x51, 0xd7, 0x1f,
	0x50, 0xd1, 0x6f, 0x1b, 0x30, 0xbc, 0xd2, 0xa8, 0xce, 0xe5, 0x9c, 0x0b, 0x0b, 0xb2, 0x07, 0xc9,
	0xac, 0xd0, 0x98, 0x2b, 0xbc, 0x75, 0x20, 0x83, 0x83, 0x91, 0x9f, 0xcf, 0x7e, 0xa0, 0x61, 0xfd,
	0x59, 0xe0, 0xdb, 0x86, 0xfe, 0x5a, 0xa3, 0xca, 0x79, 0xa3, 0x26, 0xb6, 0xe6, 0xb4, 0x22, 0xcf,
	0x21, 0x5d, 0x0b, 0x7e, 0xbb, 0x46, 0x1b, 0x8a, 0x5c, 0x27, 0x89, 0x77, 0x4c, 0x2b, 0xb2, 0x05,
	0x3d, 0x23, 0x17, 0x28, 0xb2, 0xae, 0x0b, 0x78, 0x83, 0xec, 0x00, 0x94, 0x52, 0x08, 0x2c, 0x4d,
	0x6e, 0x64, 0xd6, 0x73, 0xa1, 0x34, 0x78, 0xde, 0x4b, 0xf2, 0x02, 0x86, 0x5c, 0xdb, 0x01, 0x7a,
	0x4f, 0x16, 0x3b, 0xbe, 0x01, 0xd7, 0xac, 0x71, 0xd1, 0x8f, 0xf7, 0x84, 0xd8, 0xe1, 0x35, 0x42,
	0x8a, 0x72, 0xf1, 0x1b, 0x21, 0x47, 0xe5, 0xc2, 0x0b, 0xb1, 0xa9, 0x3b, 0x00, 0x1a, 0xd5, 0x1d,
	0x2f, 0xb1, 0xd1, 0x92, 0xb2, 0x34, 0x78, 0xa6, 0x15, 0x7d, 0x0d, 0xc3, 0x33, 0x5e, 0x2e, 0xb0,
	0xba, 0x58, 0x9b, 0x76, 0xc8, 0xf4, 0x0c, 0x12, 0xdb, 0x94, 0x3b, 0x99, 0x9f, 0xe7, 0x14, 0xd9,
	0x73, 0x22, 0x04, 0xba, 0xa2, 0x58, 0x61, 0xe0, 0x73, 0x6f, 0x3b, 0x39, 0xae, 0x73, 0x29, 0x96,
	0x5c, 0xa0, 0x9b, 0x5c, 0xc2, 0x12, 0xae, 0x2f, 0x9c, 0x4d, 0x3f, 0x43, 0x7a, 0xaa, 0xe4, 0xba,
	0x7e, 0x34, 0x9a, 0x1b, 0xb5, 0x29, 0x96, 0x0e, 0x29, 0x62, 0xde, 0x20, 0x4f, 0x21, 0x0e, 0x04,
	0x5d, 0xbf, 0x35, 0x6f, 0xd1, 0x77, 0x30, 0x70, 0xf0, 0x6f, 0xd1, 0x14, 0x7c, 0xf9, 0x80, 0x60,
	0x0f, 0xfa, 0x2b, 0x5c, 0xcd, 0x50, 0xe9, 0xac, 0xb3, 0x1b, 0x4d, 0x06, 0x07, 0x9b, 0x41, 0x74,
	0x23, 0x90, 0x35, 0x71, 0x7a, 0x08, 0xe3, 0x53, 0x34, 0x27, 0x8a, 0xa3, 0xa8, 0xce, 0xb9, 0x36,
	0xed, 0xee, 0x8a, 0xde, 0xfc, 0x52, 0xde, 0x72, 0x9b, 0x2d, 0x1a, 0xbd, 0x86, 0xcd, 0x53, 0x34,
	0x4e, 0x75, 0xfb, 0x3e, 0xc9, 0x04, 0xe2, 0xb9, 0x2d, 0x6d, 0x78, 0xc6, 0x21, 0xf1, 0xc7, 0x92,
	0x58, 0x88, 0x5b, 0x9e, 0xf9, 0x3d, 0x9e, 0x96, 0x82, 0x1e, 0xcf, 0x73, 0x05, 0xa4, 0xe1, 0x09,
	0x12, 0x5b, 0x4a, 0xda, 0x82, 0x9e, 0x83, 0x0a, 0x7f, 0x68, 0x6f, 0xd0, 0x2f, 0x0f, 0x60, 0xff,
	0xdd, 0x4a, 0x3e, 0xc1, 0x7f, 0x97, 0x5c, 0xcc, 0x97, 0xf8, 0xe6, 0xa6, 0x68, 0xbb, 0x90, 0x11,
	0x74, 0x8c, 0x0c, 0xad, 0x77, 0x8c, 0x6c, 0xbe, 0x96, 0xf6, 0xfa, 0x87, 0xfe, 0x6b, 0xf9, 0x15,
	0x86, 0x4e, 0xc6, 0x3d, 0xf0, 0xe3, 0xbf, 0x80, 0x1f, 0xff, 0x69, 0x34, 0x0f, 0x29, 0x48, 0xe6,
	0x3e, 0xb5, 0x92, 0x0b, 0x93, 0x75, 0x77, 0xa3, 0x49, 0xc4, 0x1a, 0x73, 0x16, 0x3b, 0xe4, 0x57,
	0xdf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x20, 0x68, 0x8b, 0xad, 0x76, 0x06, 0x00, 0x00,
}
